grant execute on DevSectionGet to portfolio_role 
grant execute on DevSectionSearch to portfolio_role 
grant execute on DevSectionToolGet to portfolio_role 
grant execute on DevSectionToolSearch to portfolio_role 
grant execute on DevSubsectionELementGet to portfolio_role 
grant execute on DevSubsectionGet to portfolio_role 
grant execute on DevSubsectionSearch to portfolio_role 
grant execute on DevSubsectionToolGet to portfolio_role 
grant execute on DevSubsectionToolSearch to portfolio_role 
grant execute on DevToolDelete to portfolio_role 
grant execute on DevToolGet to portfolio_role 
grant execute on DevToolTypeGet to portfolio_role 
grant execute on ProfileDelete to portfolio_role 
grant execute on ProfileGet to portfolio_role 
grant execute on ProfileUpdate to portfolio_role 
grant select on DevSection to portfolio_role 
grant select on DevSectionTool to portfolio_role 
grant select on DevSubsection to portfolio_role 
grant select on DevSubsectionElement to portfolio_role 
grant select on DevSubsectionTool to portfolio_role 
grant select on DevTool to portfolio_role 
grant select on DevToolType to portfolio_role 
grant select on Profile to portfolio_role 
grant execute on DevSubsectionQuery to portfolio_role